### ISSUE TITLE
Nomenclature Anomaly

### ISSUE THREAD

**Issue by egreen18** [meraki-analytics/lolstaticdata#29]
Good afternoon,

I noticed an issue with the nomenclature in the items JSON file while parsing through it. The field values of item.x3363.stats.cooldownReduction  are named using underscores and lowercase, whereas the standard everywhere else in the file is to use no spaces and a capital letter indicating new words. For example, there exists the field item.x3363.stats.cooldownReduction.percent_per_level , while the comparable field for boots is item.x1001.stats.cooldownReduction.percentPerLevel  . I was only able to detect one such anomaly among all of the items through my parsing.

Happy Holidays!

**Comment by jjmaldonis** [comment]
Good catch. Would you create a PR to fix the issue? It should be pretty clear what needs to be changed because it will be inconsistent with the rest of the file.

**Comment by dryancd** [comment]
I can look into it when I get back home, either tomorrow or Tuesday.

**Comment by jjmaldonis** [comment]
Closing this, see #45 for more details
