### ISSUE TITLE
Playrates not updated for latest patch

### ISSUE THREAD

**Issue by ronsiv8** [meraki-analytics/lolstaticdata#43]
Hey, currently playrates are on patch 12.7. I imagine it takes a while them, which is totally fine with me, but if you have some kind of frequency of these updates that you can share than I would appreciate it.

**Comment by GuardToad** [comment]
+1 Bel'Veth isn't added which is quite an issue.

**Comment by DarkIntaqt** [comment]
Still an issue, this is just a ping/reminder.

**Comment by jjmaldonis** [comment]
This is fixed now.
