### ISSUE TITLE
Item movespeed passives aren't being parsed/structured correctly

### ISSUE THREAD

**Issue by rdavis0** [meraki-analytics/lolstaticdata#53]
In items.json, the `passives[index].stats.movespeed` stat is set to just `0.0` for all items, as opposed to being an object with various properties for how the stat may be calculated. In cases like Zeal `3086`, which has a passive movespeed bonus, the bonus cannot be read from the item.

<pre>
"manaRegen": {
            "flat": 0.0,
            "percent": 0.0,
            "perLevel": 0.0,
            "percentPerLevel": 0.0,
            "percentBase": 0.0,
            "percentBonus": 0.0
},
<b>"movespeed": 0.0, </b>
"abilityHaste": {
            "flat": 0.0,
            "percent": 0.0,
            "perLevel": 0.0,
            "percentPerLevel": 0.0,
            "percentBase": 0.0,
            "percentBonus": 0.0
},
</pre>

**Comment by rdavis0** [comment]
@jjmaldonis Yes, I'm planning to! Currently knee-deep in the project I'm using the data for, but some of these issues will become high priority for me once I tackle a few more milestones.

**Comment by jjmaldonis** [comment]
Awesome very happy to hear it! It's always fun to be knee-deep in a project. Rob and I are heads-down working on a new product for Meraki as well, so we haven't been putting time into the lolstaticdata project. Your contributions would be greatly appreciated not only by us, but by everyone who uses this. You may have seen on the discord that a good number of people use it, so your contributions will be immediately used and appreciated by a lot of people.

We would love to add you to our contributors section, so please include that in any PR you make! I need to go back and update that as well.

**Comment by jjmaldonis** [comment]
Fixed by #57
