### ISSUE TITLE
CDN not updated

### ISSUE THREAD

**Issue by Galvantua** [meraki-analytics/lolstaticdata#63]
Seems the folder parts of the cdn (the items and champions folders) are outdated by a large margin. Idk if this the spot to put it, but I did test the script and it does pull the correct information.

**Comment by jjmaldonis** [comment]
Posting here is good. I haven't had time to see what's wrong with the script on the server but I'll try to take a look soon.

**Comment by Galvantua** [comment]
Thanks, much appreciated. Figured I'd post here instead of burying it in a discord

**Comment by jjmaldonis** [comment]
I ran the script on the server and it worked perfectly. I don't know why the data wasn't being updated. I'm going to close this, but feel free to reopen it if you're still seeing issues.

**Comment by chaodhib** [comment]
Hi. Thanks a lot for your work on this. 

Sadly, this tickets need to be opened because the data served by the CDN is quite outdated compared to what is being generated by the python scripts.

**Comment by Galvantua** [comment]
I usually jump into the riot 3rd party developers discord and mention it there, happened a few times
