### ISSUE TITLE
Small stats differences with dataDragon

### ISSUE THREAD

**Issue by APacano** [meraki-analytics/lolstaticdata#64]
Hi guys, 
I'm working on API using your data and dataDragon informations.
I've done some comparisons in code and there are few mismatches in Champion basic statistics, here's list :

- "Aurelion Sol movespeed flat statistics are different"
- "Bel'Veth mana flat statistics are different"
- "Braum hp flat statistics are different"
- "Braum healthRegen flat statistics are different"
- "Evelynn manaRegen flat statistics are different"
- "Gnar attackRange flat statistics are different"
- "Gnar attackRange per level statistics are different"
- "Jhin attackSpeed per level statistics are different"
- "Kled movespeed flat statistics are different"
- "Kled attackRange flat statistics are different"
- "K'Sante hp per level statistics are different"
- "Wukong attackSpeed flat statistics are different"
- "Mordekaiser mana flat statistics are different"
- "Viego mana flat statistics are different"

Just letting you know, can close after read.

**Comment by jjmaldonis** [comment]
Thanks! The data we have gets pulled from the wiki, so if you're able to get a hold of the people from the wiki and ask them to update the information then that's probably the fastest way to get it fixed. It may be possible for you to suggest edits to the wiki yourself as well, I don't know how their process works.
