### ISSUE TITLE
Missing 'Ornn' as the required Ally/required_ally

### ISSUE THREAD

**Issue by ViniciusNascDeMoraes** [meraki-analytics/lolstaticdata#69]
Some items in the list are Ornn Upgrades and are missing 'Ornn' as the required Ally/required_ally. Here is the items:

- Equinox
- Infinite Convergence
- Primordial Dawn

**Comment by bangingheads** [comment]
This is caused by Riot's data in the client being inaccurate. We could potentially add an override for these cases.

**Comment by jjmaldonis** [comment]
Infinite Convergence has Ornn as a required ally so it looks like this is fixed. Closing this issue.
