### ISSUE TITLE
i want to use  http://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json 

### ISSUE THREAD

**Issue by Meerkat1030** [meraki-analytics/lolstaticdata#77]
I am an aspiring developer who wants to develop using http://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json 
When I try to receive data from javascript through ajax, I get a CORS error. Is the only way to fork git and then install Python to save the data?
thank you

**Comment by jjmaldonis** [comment]
Hey, the best way to use the data is to use a script to download it to your own server.
