### ISSUE TITLE
Some Champion Skin Loading Screen splash arts do not have valid URLs

### ISSUE THREAD

**Issue by Baylem** [meraki-analytics/lolstaticdata#83]
I've done a randomization 'pick your skin' type application, however some of the loadingScreen and vintageLoadingScreen URLs have some text preventing the image from being displayed.

One example is Nami's Coven Skin:

https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions/Nami.json

The art links contain:
```
  loadingScreen: 'https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/assets/characters/nami/skins/skin51/namiloadscreen_51.pie_c_13_20.jpg',
  vintageLoadingScreen: 'https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/assets/characters/nami/skins/skin51/namiloadscreen_51_le.pie_c_13_20.jpg'

```
However, the loading screen images do not work because of the `.pie_c_13_20` string attached to the end of the name, before the file extension. If I remove the string, the links will work correctly.

[loadingScreen](https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/assets/characters/nami/skins/skin51/namiloadscreen_51.pie_c_13_20.jpg)

[loadingScreen (string removed)](https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/assets/characters/nami/skins/skin51/namiloadscreen_51.jpg)

The individual champion json's it seems to be where the links start to break. The `.pie_c_13_20` string isn't on the champions.json  (https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json) for the Coven Nami skin but it is on Nami.json (https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions/Nami.json)

**Comment by bangingheads** [comment]
This has nothing to do with the script, it is due to individual champion jsons not being updated on the CDN. The referenced json hasn't been updated since 29-Nov-2023.
The script properly generates these files, so it will be up to @jjmaldonis to help fix the CDN.

**Comment by jjmaldonis** [comment]
Alright everything is updated. I can't find anything wrong with the script, but I'll check again this week to make sure it's running.
