### ISSUE TITLE
AttackSpeed Stat type

### ISSUE THREAD

**Issue by PushaBe** [meraki-analytics/lolstaticdata#97]
I suppose since Attack Speed/HealAndShieldPower are measured in Percentages in LoL, it also has to be in a percent section rather than flat. It's a little counter intuitive to look for the Attack Speed stats in the "flat" section even though it's stacked additively (Lifesteal is also additive but is "percent" stat). In addition, [here](https://github.com/meraki-analytics/lolstaticdata/blob/master/lolstaticdata/items/pull_items_wiki.py#L283) when you parse passives, you put them into "percent". But raw stats are put in flat: [here](https://github.com/meraki-analytics/lolstaticdata/blob/master/lolstaticdata/items/pull_items_wiki.py#L395) and [here](https://github.com/meraki-analytics/lolstaticdata/blob/master/lolstaticdata/items/pull_items_wiki.py#L549)

**Comment by jjmaldonis** [comment]
At this point we are not considering changes to the format of the JSON because any format changes will result in downstream apps breaking.
